#!/usr/bin/env python3
"""Generate a page per family at /<city>/ so link previews (iMessage, Slack, etc.)
show who the page was made for and their city. Previews read the static <title>/og tags and don't run
JavaScript, so ?city=... alone can't change them.

index.html is the single source. Edit it, then run:  python3 build_cities.py
To add a family, add a line to CITIES (id must match cities.id in Supabase).
"""
import pathlib

CITIES = {
    # id: (who the page is for, city name for the preview text)
    "dallas": ("the Fife family", "Dallas"),
    "lexington": ("the Mulholland family", "Lexington"),
}

root = pathlib.Path(__file__).parent
src = (root / "index.html").read_text()

def swap(s, old, new):
    assert old in s, f"build_cities: expected text not found: {old[:60]}"
    return s.replace(old, new)

for cid, (made_for, city) in CITIES.items():
    s = src
    s = swap(s, "near Oklahoma City", f"near {city}")
    s = swap(s, "Created by Richard Magann.\">", f"Created by Richard Magann for {made_for}.\">")
    s = swap(s, '<span id="madefor"></span>', f'<span id="madefor"> for {made_for}</span>')
    s = swap(s, 'get("city")||"okc")', f'get("city")||"{cid}")')
    out = root / cid / "index.html"
    out.parent.mkdir(exist_ok=True)
    # Comment goes after the doctype so the page stays in standards mode.
    s = swap(s, "<!doctype html>\n", "<!doctype html>\n<!-- Generated by build_cities.py from ../index.html. Don't edit by hand. -->\n")
    out.write_text(s)
    print("wrote", out.relative_to(root))
